Augmented htbuild to allow easy setup of dev environment

diff --git a/bin/src-utils/htbuild b/bin/src-utils/htbuild
--- a/bin/src-utils/htbuild
+++ b/bin/src-utils/htbuild
@@ -18,8 +18,13 @@
 # along with Hypertable. If not, see <http://www.gnu.org/licenses/>
 #
 
-# Setup minimal environment on a target machine and build binary packages
+# This script sets up build environment on a target machine and/or
+# build binary packages
+
 SELF=`type -p $0`
+
+# Keeps some states of source packages, mostly for restartability
+VAR_DIR=/var/opt/htbuild
 
 # default values
 REPO_URL=git://scm.hypertable.org/pub/repos/hypertable.git
@@ -28,10 +33,13 @@ BUILD_TYPE=Release
 TESTS=core
 BUILD_SYS=`uname -s | tr A-Z a-z`
 BUILD_MACH=`uname -m`
-GENERATORS=
+WORK_DIR=htbuild-dir
+FORCE=
+
+NUM_PROCS=`grep -c processor < /proc/cpuinfo || echo 1`
 
 case $BUILD_MACH in
-  i[3456]86)    BUILD_MACH=i386
+  i[3-6]86) BUILD_MACH=i386
 esac
 
 if [ -f /etc/debian_version ]; then
@@ -47,58 +55,65 @@ get() {
   curl -L "$url" -o "$out"
 }
 
+set_installed() {
+  touch $VAR_DIR/installed/$1
+}
+
+installed() {
+  test x$FORCE = x -a -f $VAR_DIR/installed/$1
+}
+
 install_cmake() {
-  cmake --version && return 0
-  [ -f cmake.installed ] && return 0
+  installed cmake && return 0
   get http://www.cmake.org/files/v2.6/cmake-2.6.4.tar.gz cmake.tgz
   tar zxf cmake.tgz
   (cd cmake-2.6.4 && ./bootstrap --prefix=/usr && make && make install) &&
-  touch cmake.installed
+  set_installed cmake
 }
 
 install_log4cpp() {
-  [ -f log4cpp.installed ] && return 0
+  installed log4cpp && return 0
   get http://sourceforge.net/projects/log4cpp/files/log4cpp-1.0.x%20%28current%29/log4cpp-1.0/log4cpp-1.0.tar.gz/download log4cpp.tgz
   tar zxf log4cpp.tgz
   (cd log4cpp-1.0 && ./configure && make && make install) &&
-  touch log4cpp.installed
+  set_installed log4cpp
 }
 
 install_libunwind() {
-  [ -f libunwind.installed ] && return 0
+  installed libunwind && return 0
   get http://download.savannah.gnu.org/releases/libunwind/libunwind-0.99-beta.tar.gz libunwind.tgz
   tar zxf libunwind.tgz
   (cd libunwind-0.99-beta && bash configure && make && make install) &&
-  touch libunwind.installed
+  set_installed libunwind
 }
 
 install_tcmalloc() {
-  [ -f tcmalloc.installed ] && return 0
+  installed tcmalloc && return 0
   install_libunwind
   get http://google-perftools.googlecode.com/files/google-perftools-1.3.tar.gz tcmalloc.tgz
   tar zxf tcmalloc.tgz
   (cd google-perftools-1.3 && ./configure && make && make install) &&
-  touch tcmalloc.installed
+  set_installed tcmalloc
 }
 
 install_boost() {
-  [ -f boost.installed ] && return 0
+  installed boost && return 0
   get http://sourceforge.net/projects/boost/files/boost/1.39.0/boost_1_39_0.tar.bz2/download boost.tbz2
   tar jxf boost.tbz2
-  (cd boost_1_39_0 && ./bootstrap.sh --with-libraries=filesystem,iostreams,program_options,system,thread && ./bjam install) && touch boost.installed
+  (cd boost_1_39_0 && ./bootstrap.sh --with-libraries=filesystem,iostreams,program_options,system,thread && ./bjam install) && set_installed boost
 }
 
 install_bdb() {
-  [ -f bdb.installed ] && return 0
+  installed bdb && return 0
   get http://download.oracle.com/berkeley-db/db-4.7.25.tar.gz bdb.tgz
   tar zxf bdb.tgz
   (cd db-4.7.25/build_unix && ../dist/configure --enable-cxx && make &&
       make install && echo /usr/local/BerkeleyDB.4.7/lib \
-      > /etc/ld.so.conf.d/bdb.conf) && touch bdb.installed
+      > /etc/ld.so.conf.d/bdb.conf) && set_installed bdb
 }
 
 install_sigar() {
-  [ -f sigar.installed ] && return 0
+  installed sigar && return 0
   name=hyperic-sigar-1.6.3
   get http://sourceforge.net/projects/sigar/files/sigar/1.6/$name.tar.gz/download sigar.tgz
   tar zxf sigar.tgz
@@ -109,19 +124,26 @@ install_sigar() {
   esac
   cp $name/sigar-bin/lib/*sigar-$m-$BUILD_SYS.* /usr/local/lib &&
       echo /usr/local/lib > /etc/ld.so.conf.d/local.conf &&
-      touch sigar.installed
+      set_installed sigar
 }
 
 install_thrift() {
-  [ -f thrift.installed ] && return 0
+  installed thrift && return 0
   get http://hypertable.org/pub/thrift-r796538.tgz thrift.tgz
   tar zxf thrift.tgz
-  (cd thrift && ./configure --without-py --without-perl --without-ruby &&
-      make && make install) && touch thrift.installed
+
+  if [ "$SETUP_DEV_ENV" ]; then
+    confargs=
+  else
+    confargs="--without-py --without-perl --without-ruby"
+  fi
+
+  (cd thrift && ./configure $confargs && make && make install) &&
+  set_installed thrift
 }
 
 install_kfs() {
-  [ -f kfs.installed ] && return 0
+  installed kfs && return 0
   svn co http://kosmosfs.svn.sourceforge.net/svnroot/kosmosfs/trunk@364 kfs
   (cd kfs && mv CMakeLists.txt CMakeLists.txt.orig &&
       sed -e 's/_VERSIONS "1.37" "1.38")/_VERSIONS "1.37" "1.38" "1.39")/' \
@@ -129,28 +151,35 @@ install_kfs() {
           CMakeLists.txt.orig > CMakeLists.txt &&
       mkdir -p build && cd build &&
       cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=/opt/kfs .. &&
-      make install) && touch kfs.installed
+      make install) && set_installed kfs
 }
 
 build_hypertable() {
+  [ "$SETUP_DEV_ENV" ] && return 0
+
   if [ -d hypertable ]; then
     (cd hypertable && git pull)
   else
     git clone $REPO_URL hypertable || exit 1
   fi
+
   cur_branch=`cd hypertable && git symbolic-ref HEAD | sed 's/^refs.heads.//'`
+
   if [ "$cur_branch" != "$REPO_BRANCH" ]; then
     (cd hypertable && git checkout -b $REPO_BRANCH origin/$REPO_BRANCH)
   fi
+
   mkdir -p hypertable/build
+
   case $TESTS in
     core|all)    runtests="make ${TESTS}tests";;
     skip)        runtests=/bin/true;;
     *) echo "Unknown tests: $TESTS, skipped"; runtests=/bin/true;;
   esac
+
   (cd hypertable/build && cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. &&
-      make install && $runtests &&
-      ../bin/src-utils/htpkg --srcdir .. --build $BUILD_TYPE $GENERATORS)
+      make -j $((NUM_PROCS+1)) install && $runtests &&
+      ../bin/src-utils/htpkg --srcdir .. --build $BUILD_TYPE ${GENERATORS[*]})
 }
 
 disable_prelink() {
@@ -163,7 +192,7 @@ disable_prelink() {
 
 rpm_setup_repos() {
   disable_prelink
-  yum install -y curl curl-devel
+  yum install -y curl curl-devel || exit 1
 }
 
 install_dev_env_from_src() {
@@ -175,8 +204,12 @@ install_dev_env_from_src() {
   install_sigar
   install_thrift
   install_kfs
-  # need to disable selinux (on fedora/centos etc.)
-  type setenforce && setenforce 0
+  # need to disable selinux (on Fedora/CentOS etc.) or ldconfig would fail
+  # because some libraries like Berkeley DB shared libraries are installed
+  # in a non-standard directory if compiled from source. This is and is
+  # required for regression tests to finish properly. The normal usage of
+  # binary packages themselves doesn't require selinux to be off.
+  type setenforce 2>/dev/null && setenforce 0
   ldconfig
 }
 
@@ -184,25 +217,57 @@ rpm_install_dev_env() {
   yum install -y gcc-c++ make bzip2-devel zlib-devel expat-devel git-core \
       libevent-devel readline-devel ncurses-devel bison flex pkgconfig \
       subversion rpm-build xfsprogs-devel openssl-devel
+
   case `yum info cmake | grep Version:` in
     Version:*2.6*) yum install -y cmake;;
   esac
+
+  if [ "$SETUP_DEV_ENV" ]; then
+    yum install -y perl-Bit-Vector php python-devel ruby-devel graphviz doxygen
+    get http://dag.wieers.com/rpm/packages/perl-Class-Accessor/perl-Class-Accessor-0.31-1.el5.rf.noarch.rpm perlCA.rpm
+    yum localinstall perlCA.rpm
+
+    case `javac -version 2>&1` in
+      javac*1.6);;
+      *) echo "Hypertable requires JDK 1.6 for Java development";;
+    esac
+  fi
+
   install_dev_env_from_src
 }
 
 deb_setup_repos() {
-  apt-get update
+  apt-get update || exit 1
   apt-get install -y curl
 }
 
 deb_install_dev_env() {
-  apt-get install -y g++ make git-core liblog4cpp5-dev libevent-dev zlib1g-dev \
-      libbz2-dev libexpat1-dev libncurses-dev libreadline5-dev bison flex \
-      pkg-config subversion xfslibs-dev libssl-dev rpm
-  touch log4cpp.installed
+  apt-get install -y g++ make git-core libevent-dev zlib1g-dev libbz2-dev \
+      libexpat1-dev libncurses-dev libreadline5-dev bison flex pkg-config \
+      subversion xfslibs-dev libssl-dev rpm
+  apt-get -y install liblog4cpp5-dev && set_installed log4cpp
+
   case `aptitude show cmake | grep Version:` in
-    Version:*2.6*) apt-get install -y cmake && touch cmake.installed;;
+    Version:*2.6*) apt-get install -y cmake && set_installed cmake;;
   esac
+
+  case `aptitude search 'libdb4.*\+\+-dev'` in
+    *libdb4.7++-dev*) apt-get install -y libdb4.7++-dev && set_installed bdb;;
+    *libdb4.6++-dev*) apt-get install -y libdb4.6++-dev && set_installed bdb;;
+  esac
+
+  case `aptitude search 'libboost1.*-dev'` in
+    *libboost1.37-dev*)
+      apt-get install -y libboost1.37-dev && set_installed boost;;
+    *libboost1.35-dev*)
+      apt-get install -y libboost1.35-dev && set_installed boost;;
+  esac
+
+  if [ "$SETUP_DEV_ENV" ]; then
+    apt-get install -y ant php5 php5-cli ruby ruby-dev libhttp-access2-ruby \
+        libbit-vector-perl graphviz doxygen sun-java6-jdk
+  fi
+
   install_dev_env_from_src
 }
 
@@ -218,17 +283,35 @@ do_linux_with_deb() {
   build_hypertable
 }
 
+install_dev_env() {
+  SETUP_DEV_ENV=1
+  do_$TARGET
+}
+
 do_remote() {
   [ "$BUILD_HOST" ] || { echo "--host <host> required"; exit 1; }
+
   while true; do
-    scp $SSH_OPTS $SELF root@$BUILD_HOST:
+    ssh $SSH_OPTS root@$BUILD_HOST mkdir -p $WORK_DIR
     [ $? = 0 ] && break;
     echo "Waiting for $BUILD_HOST to be ready..."
     sleep 3
   done
-  ssh $SSH_OPTS root@$BUILD_HOST bash -x `basename $SELF` --build $BUILD_TYPE \
-      --repo $REPO_URL --branch $REPO_BRANCH --tests $TESTS $GENERATORS
-  scp $SSH_OPTS root@$BUILD_HOST:hypertable/build/hypertable-* .
+
+  case $FORCE in
+    1|[yY]*)    force=--force;;
+    *)          force=;;
+  esac
+
+  scp $SSH_OPTS $SELF root@$BUILD_HOST:$WORK_DIR
+  ssh $SSH_OPTS root@$BUILD_HOST bash -x $WORK_DIR/`basename $SELF` \
+      --build $BUILD_TYPE --repo $REPO_URL --branch $REPO_BRANCH \
+      --tests $TESTS --workdir $WORK_DIR --install "'${INSTALLS[*]}'" \
+      $force ${GENERATORS[*]}
+
+  if [ ${#INSTALLS} -eq 0 ]; then
+    scp $SSH_OPTS root@$BUILD_HOST:$WORK_DIR/hypertable/build/hypertable-* .
+  fi
 }
 
 run_ami() {
@@ -240,10 +323,11 @@ instance_type() {
   # Amazon should pick the smallest instance type available for a
   # given architecture if instance type is not specified
   t=`ec2-describe-images $1 | cut -f8`
+
   case $t in
     i386)       echo m1.small;;
     x86_64)     echo m1.large;;
-    *)          echo "unknown instance type: $t"; exit 1;;
+    *)          echo "Unknown instance type: $t"; exit 1;;
   esac
 }
 
@@ -272,7 +356,11 @@ do_ami() {
 
 sanity_check() {
   type do_$TARGET > /dev/null || { echo "$TARGET not supported"; exit 1; }
-  [ "$GENERATORS" ] || { echo "one or more generators required"; exit 1; }
+
+  if [ ${#INSTALLS} -eq 0 -a ${#GENERATORS} -eq 0 ]; then
+    echo "one or more generators required"
+    exit 1
+  fi
 }
 
 [ $# -gt 0 ] || {
@@ -286,29 +374,48 @@ sanity_check() {
   echo "  --mach <machine>      i386|x86_64|etc..."
   echo "  --build <type>        Release|Debug|RelWithDebInfo"
   echo "  --repo <url>          git repo url"
-  echo "  --branch <branch>     git repo branch"
+  echo "  --branch <branch>     git repo branch/commit"
   echo "  --tests <tests>       core|all|skip"
+  echo "  --workdir <dir>       working directory"
+  echo "  --install <src>       source package to install (multiple options)"
+  echo "  --force               force reinstall source packages"
   exit 1;
 }
 
 while [ $# -gt 0 ]; do
   case $1 in
-    --ami)      BUILD_AMI=$2;   shift;;
-    --host)     BUILD_HOST=$2;  shift;;
-    --target)   TARGET=$2;      shift;;
-    --mach)     BUILD_MACH=$2;  shift;;
-    --build)    BUILD_TYPE=$2;  shift;;
-    --repo)     REPO_URL=$2;    shift;;
-    --branch)   REPO_BRANCH=$2; shift;;
-    --tests)    TESTS=$2;       shift;;
-    -*) echo "unknown option $1"; exit;;
-    *)  GENERATORS="$GENERATORS $1";;
+    --ami)      BUILD_AMI=$2;   TARGET=ami;     shift;;
+    --host)     BUILD_HOST=$2;  TARGET=remote;  shift;;
+    --target)   TARGET=$2;                      shift;;
+    --mach)     BUILD_MACH=$2;                  shift;;
+    --build)    BUILD_TYPE=$2;                  shift;;
+    --repo)     REPO_URL=$2;                    shift;;
+    --branch)   REPO_BRANCH=$2;                 shift;;
+    --tests)    TESTS=$2;                       shift;;
+    --workdir)  WORK_DIR=$2;                    shift;;
+    --install)  INSTALLS[${#INSTALLS[*]}]=$2;   shift;;
+    --force)    FORCE=1;;
+    -*)         echo "Unknown option: $1";      exit;;
+    *)          GENERATORS[${#GENERATORS[*]}]=$1;;
   esac
   shift
 done
 
+echo "$0 ($TARGET) started:" `date`
+
 sanity_check
 
-echo "$0 started:" `date`
-do_$TARGET
+if [ x$BUILD_AMI = x -a x$BUILD_HOST = x ]; then
+  mkdir -p $VAR_DIR/installed || exit 1
+  mkdir -p $WORK_DIR && cd $WORK_DIR
+fi
+
+if [ ${#INSTALLS} -eq 0 -o "$BUILD_AMI" -o "$BUILD_HOST" ]; then
+  do_$TARGET
+elif [ ${#INSTALLS} -gt 0 ]; then
+  for src in ${INSTALLS[*]}; do
+    install_$src
+  done
+fi
+
 echo "$0 finished:" `date`
